# Generated by Django 4.2.5 on 2023-10-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_team_score', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('second_team_score', models.IntegerField(default=0)),
                ('sports_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('game_status', models.CharField(choices=[('BEFORE', '경기전'), ('FIRST_HALF', '전반전'), ('SECOND_HALF', '후반전'), ('OVER', '종료')], default='BEFORE', max_length=11)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('scored_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo_image_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
    ]
