# Generated by Django 4.2.5 on 2023-10-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
