# Generated by Django 4.2.5 on 2024-02-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheerTalk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('content', models.CharField(max_length=255)),
                ('is_blocked', models.BooleanField(default=False)),
                ('game_team_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cheer_talks',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reported_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('UNCHECKED', 'unchecked'), ('VALID', 'valid'), ('INVALID', 'invalid'), ('PENDING', 'pending')], max_length=255)),
                ('cheer_talk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.cheertalk', unique=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
