# Generated by Django 4.2.5 on 2024-02-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
        ('sport', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quarter_changed_at', models.DateTimeField(auto_now=True)),
                ('game_quarter', models.CharField(default='시작 전', max_length=255)),
                ('state', models.CharField(choices=[('PLAYING', 'playing'), ('FINISHED', 'finished'), ('SCHEDULED', 'scheduled')], default='SCHEDULED', max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.league')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.sport')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cheer_count', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game')),
                ('league_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.leagueteam')),
            ],
            options={
                'db_table': 'game_teams',
            },
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField()),
                ('is_captain', models.BooleanField(default=False)),
                ('game_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.gameteam')),
            ],
            options={
                'db_table': 'lineup_players',
            },
        ),
    ]
