# Generated by Django 4.2.5 on 2024-03-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='quarter_changed_at',
            field=models.DateTimeField(),
        ),
    ]
