# Generated by Django 4.2.5 on 2023-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('is_administrator', models.BooleanField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
