# Generated by Django 4.2.5 on 2024-02-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.organization')),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='LeagueSport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.league')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.sport')),
            ],
            options={
                'db_table': 'league_sports',
            },
        ),
    ]
