# Generated by Django 4.2.5 on 2024-02-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='in_progress_round',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='max_round',
            field=models.IntegerField(null=True),
        ),
    ]
