# Generated by Django 4.2.5 on 2024-02-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_image_url', models.CharField(max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='league.league')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.organization')),
            ],
            options={
                'db_table': 'league_teams',
            },
        ),
        migrations.CreateModel(
            name='LeagueTeamPlayer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.IntegerField(null=True)),
                ('league_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.leagueteam')),
            ],
            options={
                'db_table': 'league_team_players',
            },
        ),
    ]
