# Generated by Django 4.2.5 on 2024-02-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('record_type', models.CharField(choices=[('SCORE', 'score'), ('REPLACEMENT', 'replacement')], max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game')),
                ('game_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.gameteam')),
                ('recorded_quarter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sport.quarter')),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('lineup_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.lineupplayer')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='record.record')),
            ],
            options={
                'db_table': 'score_records',
            },
        ),
        migrations.CreateModel(
            name='ReplacementRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin_lineup_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.lineupplayer')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='record.record')),
                ('replaced_lineup_player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.lineupplayer')),
            ],
            options={
                'db_table': 'replacement_records',
            },
        ),
    ]
